name: Build TangSengDaoDaoWeb EXE for Windows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable Yarn (via Corepack)
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build frontend
        run: yarn build

      - name: Build Windows EXE
        run: cd apps/web && yarn run build-ele:win

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: tsdd-win-exe
          path: apps/web/dist_electron/win-unpacked/*.exe

